[package]
name = "mio_httpc"
version = "0.2.3"
authors = ["sergej jurecko <sergej.jurecko@gmail.com>"]
description = "mio_httpc is a fully async http client running on top of mio only."
repository = "https://github.com/SergejJurecko/mio_httpc"
readme = "README.md"
keywords = ["mio", "http", "client", "async", "websocket"]
categories = ["network-programming"]
license = "MIT/Apache-2.0"
documentation = "http://docs.rs/mio_httpc"
homepage = "https://github.com/SergejJurecko/mio_httpc"

[features]
# Default does not work.
default = []

# Must pick one and only one!
rustls = ["tls-api-rustls"]
native = ["tls-api-native-tls"]
openssl = ["tls-api-openssl"]

[dependencies]
mio = "0.6"
httparse = "1"
byteorder = "1"
libc = "0.2"
fnv = "1"
rand = "0.3"
http = "0.1"
tls-api = "0.1"
itoa = "0.3"
data-encoding = "2.1"
failure = "0.1"
smallvec = "0.6"

# Do not include directly. Use one of the features.
tls-api-rustls = { version = "0.1.11", optional = true}
tls-api-native-tls = { version = "0.1.11", optional = true}
tls-api-openssl = { version = "0.1.11", optional = true}

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.4"
core-foundation-sys = "0.4"

[dev-dependencies]
matches = "0.1"
