[package]
name = "mio_httpc"
version = "0.2.3"
authors = ["sergej jurecko <sergej.jurecko@gmail.com>"]
description = "mio_httpc is a fully async http client running on top of mio only."
repository = "https://github.com/SergejJurecko/mio_httpc"
readme = "README.md"
keywords = ["mio", "http", "client", "async", "websocket"]
categories = ["network-programming"]
license = "MIT/Apache-2.0"
documentation = "http://docs.rs/mio_httpc"
homepage = "https://github.com/SergejJurecko/mio_httpc"
build = "build.rs"

[features]
# Default does not work.
default = []
native = ["native-tls"]
# rustls = ["webpki-roots"]

[dependencies]
mio = "0.6"
httparse = "1"
byteorder = "1"
libc = "0.2"
fnv = "1"
rand = "0.3"
http = "0.1"
itoa = "0.3"
data-encoding = "2.1"
failure = "0.1"
smallvec = "0.6"
md5 = "0.3"

webpki-roots = {version = "0.13", optional = true}
rustls = { version = "0.11", features = ["dangerous_configuration"], optional = true}
openssl      = { version = "0.10.*", optional = true, features = ["v102", "v110"] }
native-tls   = { version = "0.*", optional = true}


[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.4"
core-foundation-sys = "0.4"

[dev-dependencies]
matches = "0.1"
