[package]
name = "httpc"
version = "0.1.0"
authors = ["sergej jurecko <sergej.jurecko@gmail.com>"]

[dependencies]
mio = "0.6"
# url = "1"
httparse = "1"
quick-error = "1"
byteorder = "1"
libc = "0.2"
fnv = "1"
time = "0.1"
rand = "0.3"
http = "0.1"
tls-api = {git = "https://github.com/SergejJurecko/rust-tls-api.git"}
itoa = "0.3"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.4"
core-foundation-sys = "0.4"

[dev-dependencies]
matches = "0.1"
